/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-background': '#191c20',
        'outline-variant': '#bacac3',
        tertiary: '#984718',
        background: '#f8f9ff',
        'inverse-surface': '#2e3135',
        'on-primary-fixed': '#002019',
        'on-tertiary-fixed': '#341100',
        'surface-container-highest': '#e1e2e8',
        'primary-container': '#00c9a7',
        'inverse-primary': '#38debb',
        outline: '#6b7a75',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-container': '#3a6e60',
        'on-surface': '#191c20',
        'on-primary-container': '#004e40',
        'on-surface-variant': '#3c4a45',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffdbcb',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9ff',
        surface: '#f8f9ff',
        secondary: '#34685a',
        'tertiary-container': '#ff9862',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#002019',
        'surface-container-high': '#e7e8ee',
        'on-secondary-fixed-variant': '#194f42',
        'primary-fixed-dim': '#38debb',
        'secondary-container': '#b7eedc',
        'tertiary-fixed-dim': '#ffb692',
        'surface-container': '#eceef3',
        'surface-container-lowest': '#ffffff',
        primary: '#006b58',
        'on-primary-fixed-variant': '#005142',
        'surface-variant': '#e1e2e8',
        'inverse-on-surface': '#eff0f6',
        'on-tertiary-fixed-variant': '#793100',
        'secondary-fixed': '#b7eedc',
        'surface-dim': '#d8dae0',
        'secondary-fixed-dim': '#9cd1c0',
        'on-tertiary-container': '#762f00',
        'surface-container-low': '#f2f3f9',
        'surface-tint': '#006b58',
        'primary-fixed': '#5ffbd6',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
